spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false


  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_INITDB_DATABASE}

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRATION_MS} 

---
spring:
  config:
    activate:
      on-profile: test

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration
      - org.springframework.boot.autoconfigure.mongo.MongoHealthContributorAutoConfiguration
      
  data:
    mongodb:
      database: ${MONGO_TEST_DATABASE}
      uri: ${MONGO_TEST_URI}

jwt:  
  secret: test-jwt-secret
  expiration-ms: 3600000

    

