services:
  app:
    build: .
    container_name: lexora-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres
      - mongo

  postgres:
    image: postgres:16
    container_name: lexora-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  mongo:
    image: mongo:7
    container_name: lexora-mongo
    ports:
      - "27017:27017"
